# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-28 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked', to='wish_app.User'),
        ),
    ]
