# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-25 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFueling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('odometer', models.IntegerField()),
                ('trip_meter', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gallons', models.DecimalField(decimal_places=3, max_digits=5)),
                ('hwy', models.BooleanField()),
                ('city', models.BooleanField()),
                ('off', models.BooleanField()),
                ('mpg', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('ppg', models.DecimalField(decimal_places=3, max_digits=4)),
                ('not_full', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('odometer', models.IntegerField()),
                ('provider', models.CharField(max_length=255)),
                ('maint', models.TextField()),
                ('is_oilchg', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('odometer', models.IntegerField()),
                ('logstart', models.DateField()),
                ('lastoilchg', models.IntegerField()),
                ('hwy_mpg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('city_mpg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('off_mpg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('combine_mpg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('oil_used', models.CharField(max_length=100)),
                ('tires', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('trip_store', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('gallons_store', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
