# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-25 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclefueling',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_records', to='recordtracker.VehicleStats'),
        ),
        migrations.AddField(
            model_name='vehiclemaint',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='recordtracker.VehicleStats'),
        ),
    ]
