# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-25 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtracker', '0002_auto_20190625_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestats',
            name='city_mpg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclestats',
            name='combine_mpg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclestats',
            name='hwy_mpg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclestats',
            name='lastoilchg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclestats',
            name='off_mpg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
