# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtracker', '0003_auto_20190625_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclefueling',
            name='combine',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
