# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtracker', '0004_vehiclefueling_combine'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaint',
            name='oil_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
